### ISSUE TITLE
Default restore sessionStorage restore does not default to empty object and breaks the middleware.

### ISSUE THREAD

**Issue by anlauren** [jerelmiller/redux-simple-auth#15]
Hi,
It might be something wront with my set up, but by looking at the code it seems to me that there's a problem in hte default sessionStorage .
The sample of code I am using are these:
```
(...)
import { createAuthenticator } from 'redux-simple-auth';
export const authenticator = createAuthenticator({
	name: 'credentials',
	authenticate(data){
request.post(`${process.env.PROXY_HOST}:${process.env.PROXY_PORT}/api/auth/login`, data)
		.then(data => {
			return data;
		});
	},
	restore(data){
		console.log('restoring', data);
		if(data && data.token) {
			return Promise.resolve(data);
		} else {
			return Promise.reject();
		}
	}
});
(...)
const authMiddleware = createAuthMiddleware({ authenticator });
const store = createStore(rootReducer, initialState, applyMiddleware(thunkMiddleware, authMiddleware));
```
and there I get: 

> Electrode ReduxRouterEngine Error: TypeError: Cannot read property 'authenticated' of undefined at node_modules/redux-simple-auth/lib/middleware.js:81:49.]

I have looked in the file and in this lines: 
```
 return function (_ref2) {
    var dispatch = _ref2.dispatch,
        getState = _ref2.getState;

    var _storage$restore = storage.restore(),
        _storage$restore$auth = _storage$restore.authenticated,
        authenticated = _storage$restore$auth === undefined ? {} : _storage$restore$auth;
```
and with this, if nothing is returned it is yet not possible to check the authenticated status.
the simple fix I see would be to default to an empty object if the restore does not return an object but I might not beeing seeing the great schemes of things around that.

**Comment by jerelmiller** [comment]
Hey @anlauren. I have indeed determined this is a problem.

The default session store is an adaptive store and will attempt to use localStorage if available, but fallback on cookie storage if not. I have reproduced this issue with the cookie store. I will get a fix out immediately. Thanks for catching this!

**Comment by jerelmiller** [comment]
@anlauren I have pushed an update to fix this issue as v0.2.1. Let me know if this works out for you.

**Comment by anlauren** [comment]
@jerelmiller allright I try that now.
I think it was returning null because I am trying to set up the store in a server side rendering, therefore no cookie or storage is present. I don't know how all this is going to connect fine alltogether

**Comment by jerelmiller** [comment]
Ah that is a very interesting use case. I haven't quite yet tried this library in a server-side rendered environment. I'd love to put it on my TODO list.

If you find the default session store lacking, you might try [implementing your own](https://github.com/jerelmiller/redux-simple-auth#implementing-a-custom-session-store).

Unfortunately this library is still very young so it doesn't quite have all the bells and whistles. I'd love to get a solution that would work for SSR so if you have any ideas, I'd love to hear them!

**Comment by anlauren** [comment]
Sure I will le you know what solution I find.
My thought is, on server side: populate the redux state with a first "fake store" with the cookie in the request: if it is not there we initiate as not authorized, either way put the right data in the store.
Then the client HTML will be populated witht that and the Store on the client side can set up with the initial state what needs to be set up.
It will be tricky, but it should be doable

**Comment by anlauren** [comment]
So:
To be able to SSR page if the user has a session on the client side, I created a second middleware on the server side that uses a dummy store, just so the session information are available during the pre render:

```
export const SSRAuthenticator = createAuthenticator({
	name: AUTHENTICATOR_NAME,
	authenticate(){
		/*this should not be used in anyway*/
		console.error('Trying to authenticate on server-side');//eslint-disable-line
		return Promise.reject();
	},
	restore(data){
		if(data && data.auth_token) {
			return Promise.resolve(data);
		} else {
			return Promise.reject();
		}
	}
});

export const SSRstorageCreator = (request) => ({
	name: COOKIE_STORE_NAME,
	persist() {}, /* no op really, we are on the server side.*/
	restore() {/* we read any session info the client sent in his request */
		return request.cookies && request.cookies[COOKIE_STORE_NAME] && JSON.parse(request.cookies[COOKIE_STORE_NAME]);
	}
});

```
also @jerelmiller , on the Client side there's something that could be added (or I did not find it).
When you have a failed logged authentification, can't the auth map it to the store? 
Either way We have to wrap the authenticator in a more complexe structure to dispatch that an error occured.
Beeing able to dispatch something or read a state on authentication reject would be good, could also be good on auth accepted but that we can deduct from the state of the store.

**Comment by jerelmiller** [comment]
Good call on exporting that. I'll make that improvement as well.

Apologies I haven't been much help on the SSR side. I actually haven't done much SSR myself so I'm not as familiar with some of the techniques and challenges. I have a general idea of the workflow, but I'm by no means an authority on the subject yet.

That being said, you found a great way to "watch" when authentication fails. The gist is that if the promise returned from the authenticate or restore functions are rejected, it will dispatch the `AUTHENTICATE_FAILED` action. This updates the `session` state and changes the `isAuthenticated` state from `true` to `false` (if it was `true` before).

If you do ever need to read from the session state directly there are some handy [selectors](https://github.com/jerelmiller/redux-simple-auth#selectors) exported that should allow you to easily access the session state.

**Comment by jerelmiller** [comment]
@anlauren I've gone ahead and released v0.2.2 that now exports the action types. You should now easily be able to import and use from the library directly!

```javascript
import { actionTypes } from 'redux-simple-auth'

actionTypes.AUTHENTICATE_FAILED
```

**Comment by anlauren** [comment]
It is working fine :)

**Comment by jerelmiller** [comment]
Glad to hear!
