### ISSUE TITLE
What is the purpose of the store enhancer?

### ISSUE THREAD

**Issue by ieugen** [jerelmiller/redux-simple-auth#21]
Hello, 

It's not clear to me what is the purpose of the store enhancer. Could you please elaborate on the use cases that it solves?

Thanks,

**Comment by jerelmiller** [comment]
Hey @ieugen, thanks for your interest in the project!

That is a very good question and reading back through the docs, I can see why you are confused.

The store enhancer is meant to be used if you need the state of the redux store initialized with the data within the storage device. I noticed you opened #20, and I believe it may help you solve that issue.

Without the store enhancer, the middleware will run _after_ initialization of the redux store. This means that the initial state will be set as the defaults.

If you want to initialize the store state with the data from the storage device, the store enhancer does just that.

Does that make sense? If you have suggestions for making this more clear in the documentation, I'd love to know what I can do to make this better!

**Comment by ieugen** [comment]
Hi, 

Thank you for the explanation. I eventually ended up at this conclusion myself after going through the docs. I think adding this explanation to the docs should be enough. The name `enhancer` is a bit misleading since it is used mainly for initialization. 

Regards,
