### ISSUE TITLE
Can I avoid storing the token in redux store?

### ISSUE THREAD

**Issue by ieugen** [jerelmiller/redux-simple-auth#22]
Hello, 

According to the docs: 

> Any data resolved with the promise will be stored and accessible via the session state. 

I have the following code: 

````
function extractTokenAndPubKey(response) {
  if (response.data && response.data.generateToken && response.data.generateToken.token ) {
    let { token, publicKey } = response.data.generateToken;
    return Promise.resolve( processJwt(token, publicKey))
  }
  return Promise.reject()
}


/**
* Implement authenticator for
* https://github.com/jerelmiller/redux-simple-auth/#actions
*/
const authenticator = createAuthenticator({
  name: 'credentials',
  authenticate(credentials) {
    return apollo.mutate({
        mutation: TOKEN_MUTATION,
      variables: {
        input: credentials
      },
      operationName: "generateToken"
      })
      .then(extractTokenAndPubKey)
  },
  restore(data) {
    return restoreJwt(data)
  }
});
````

And I get the token stored inside JS. I do believe that this is a security risk as any JS code from any domain can read the token. LocalStorage is limited to only the same domain origin scripts. 

I believe that the token should not be stored in redux. I still need to investigate and make sure that is true. If it is, then we have a security risk. 

Regards,

**Comment by jerelmiller** [comment]
Hey @ieugen,

You can certainly avoid storing the token directly, but your authenticator's `restore` method would need to know how to take whatever you do store with `redux-simple-auth` and ask your server if you are logged in. As long as that `restore` function returns a resolved promise, you are considered authenticated.

In some of the apps that I have built, we have successfully been able to store the token on the frontend to determine whether a user has a valid session. This approach is popular with libraries like [Ember Simple Auth](https://github.com/simplabs/ember-simple-auth) (the influence behind this library) and [Auth0](https://auth0.com/). Check out [this Auth0 blog post](https://auth0.com/blog/adding-authentication-to-your-react-flux-app/). You'll see the recommendation here as well to use local storage to store the token.

Like you said, local storage should only be available for the current domain. You just have to be careful that your web app doesn't allow execution of arbitrary JavaScript. React should already handle this out of the box.

I'd definitely encourage you to take a look at best practices for securing the token. If you do find anything that would help with this library that it doesn't already do, I'd love to hear it!

**Comment by ieugen** [comment]
Thanks for the feedback. I'll see what I can do.

**Comment by jerelmiller** [comment]
I think I totally misunderstood your question the first time around. Apologies, it was late and apparently I wasn't reading very closely.

When I first read this, I read this as not storing the token in the _storage_ device, but I see what you actually mean is not storing the token in the redux store itself. Again, so sorry about my misunderstanding.

I wonder if it makes sense to add some configuration that would allow you to blacklist a set of keys that wouldn't actually be stored in the redux store. The trick in this case would be figuring out how to naturally get state out of the storage device when you need it.

I'll definitely think about this a bit more. Again, apologies for my misunderstanding the first time and thanks for the suggestion.
