### ISSUE TITLE
Provide session storage 

### ISSUE THREAD

**Issue by ieugen** [jerelmiller/redux-simple-auth#24]
Hi, 

As per OWASP recommendations, the library should allow us to store a refresh token or even an access token in the session storage so it is removed when the browser is closed. 

Developers should use local storage to store tokens only on trusted machines (a.k.a when implementing a feature like 'Keep me logged in on this machine'. 

On the back-end these long term tokens should be stored and a protocol should be placed for invalidation.

[1] https://www.owasp.org/index.php/JSON_Web_Token_(JWT)_Cheat_Sheet_for_Java

**Comment by jerelmiller** [comment]
Hey @ieugen. Great suggestion!

I have just published version [v0.3.0](https://github.com/jerelmiller/redux-simple-auth/releases/tag/v0.3.0) that now exports a `sessionStorage` option.

I've updated the [documentation](https://github.com/jerelmiller/redux-simple-auth#built-in-session-stores). Feel free to update to the new version and you should now be able to use this.
