### ISSUE TITLE
"authenticate" funtion didn't store any error when an authentication failed

### ISSUE THREAD

**Issue by TerryTran** [jerelmiller/redux-simple-auth#26]
Hi,
I'm using your library to implement authentication for my project. Here are my codes for authentication: https://gist.github.com/TerryTran/3f8ea8d8e95481d60154a3824dba9dcc

According to above codes, you can see when authentication process failed I call `Promise.reject(error.graphQLErrors)` to pass error information but it's didn't store in redux.
Could you give me a solution (An example how can I store error and get it later) for this?

Thanks!

**Comment by jerelmiller** [comment]
Hey @TerryTran!

To answer your question, there isn't currently a way to get the error. Right now anything rejected from the promise is ignored. I definitely think this is a great use case though! I will try to plan to get an update in over the next couple days to support this.

Thanks for using the library!

**Comment by jerelmiller** [comment]
Hey @TerryTran 

Just wanted to let you know that I just published a release that now allows you to get the error. Simply `import { getLastError } from 'redux-simple-auth'` and pass it your state to get it. 

Hopefully this helps!

**Comment by TerryTran** [comment]
Great! I will check it. Thanks!
