### ISSUE TITLE
Extend the API with invalidate

### ISSUE THREAD

**Issue by muntact** [jerelmiller/redux-simple-auth#33]
Hi, I've been using redux simple auth for a couple of weeks now (thanks for the lib by the way :) ) , and i've been using a password grant flow simmilar to what is documented in the ember simple auth library.

And today i've just noticed that the authenticator i've built up has an invalidate method, however i'm kind of jumping through some hoops to call that function myself. Would it instead be possible to extend the authenticator API surface to include an `invalidate` method and watch for the `invalidateSession` action in the middleware and conditionally call the promise if it exists. 

extended createAuthenticator:
```js 
{
    name,
    restore = () => Promise.reject(),
    authenticate = () => Promise.reject(),
    // return a resolved promise by default if your authenticator doesn't have any cleanup...
    invalidate = () => Promise.resolve(),
  } = {}) => { 
//....
 return {
    name,
    restore,
    authenticate,
    invalidate,
  }
}
```

extended middleware:
```js
import { AUTHENTICATE, FETCH, INVALIDATE_SESSION } from './actionTypes'

// ...    
switch (action.type) {
  case INVALIDATE_SESSION:
    // maybe extract this dupl code from the authenticate method :) 
    const authenticator = findAuthenticator(action.meta.authenticator)
       if (!authenticator) {
            throw new Error(
              `No authenticator with name \`${action.meta.authenticator}\` ` +
                'was found. Be sure you have defined it in the authenticators ' +
                'config.'
            )
          }
          
          // maybe pass the payload for API parity?
          return authenticator
            .invalidate(action.payload)
 }
    
```
I'm happy to raise a PR to provide this code in a more legit way if you're open to it. 

Additionally I'd also be interested in contributing back the password grant authenticator in ES6 / discussing contributions if you think this lib is the right place for it.

**Comment by jerelmiller** [comment]
Hey @muntact. Thanks for using the library! I'm glad you are getting some use from it.

Absolutely I think that would be useful! I thought this was already in there. I vaguely remember writing code for it, but maybe I ripped it out at some point 🤔 ?

Anyways, I'd be happy if you wanted to contribute back! I think passing the session data definitely makes sense, much like the `restore` behavior exists. I know I'd love to get into some of the oauth solutions in place, but I haven't been able to find the time to do so.
