### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by cyberwombat** [jerelmiller/redux-simple-auth#55]
I am integrating Redux Simple Auth in my app and its now failing with this error:
   
    ReferenceError: regeneratorRuntime is not defined
    (anonymous function)
    node_modules/redux-simple-auth/lib/authenticators/credentials.js:67
      64 |   }, headers),
      65 |   body: transformRequest(credentials)
      66 | }).then(function () {
    > 67 |   var _ref2 = _asyncToGenerator(regeneratorRuntime.mark(function _callee(response) {
      68 |     var json;
      69 |     return regeneratorRuntime.wrap(function _callee$(_context) {
      70 |       while (1) {

I am using react-scripts v1.1.1.

It appears that you transpiled the code in a way that react-scripts cannot handle. As a workaround I manually copied all the `src` files in my where they transpile without error. I am not sure what the fix is but it would be nice to use this package with `react-scripts`.

Thanks

**Comment by jerelmiller** [comment]
Hey @cyberwombat! Thanks for checking out the library!

Could you get me some of the relevant code for how you are using the library? It appears you are trying to import the credentials authenticator. I've been running the latest version of this library with some projects successfully using `react-scripts` v1.1.1 as well. That being said, maybe there is something I missed.

Any more information you can give me with how you are setting up the middleware, authenticators, etc would be great help!

**Comment by jerelmiller** [comment]
@cyberwombat after digging a bit further, it looks like I used `async/await` with the update to the credentials authenticator, but didn't realize it didn't include the runtime. I've fixed this issue and pushed v0.6.6 to fix the issue. Let me know if the new version fixes it for you. Thanks for bringing the issue up!

**Comment by cyberwombat** [comment]
Cool, that did the trick. Thanks!
